### ISSUE TITLE
please rename the repo

### ISSUE THREAD

**Issue by amueller** [openml/openml.org#1]
cloning a repo called "website" is really not that helpful ;)

**Comment by joaquinvanschoren** [comment]
:)

renamed it openml.org
Better?

**Comment by janvanrijn** [comment]
Isn't this the deprecated repo? Should we just remove it ibstead?

Op woensdag 17 oktober 2018 heeft Joaquin Vanschoren <
notifications@github.com> het volgende geschreven:

**Comment by joaquinvanschoren** [comment]
No, this is a new one. You can see it only has 40 commits :)

Can I close this?

**Comment by janvanrijn** [comment]
Cool. I will check it out soon
