### ISSUE TITLE
Make a fast feedback issue

### ISSUE THREAD

**Issue by joaquinvanschoren** [openml/openml.org#118]
For user to give quick feedback

**Comment by prabhant** [comment]
We can do it in several ways:
- Email.
- Issue template for openml.org on GitHub.
- A react form on website

**Comment by joaquinvanschoren** [comment]
This should be as low-threshold as possible. It should also work for people without a GitHub account. I would go with a button that opens up a popup/modal with a form. The form can have a link to the github issue tracker for those that prefer that. WDYT?

**Comment by prabhant** [comment]
Sounds good, But where do we want the form results to come? Email?

**Comment by joaquinvanschoren** [comment]
Yes, a simple form that sends an email would work.

**Comment by joaquinvanschoren** [comment]
I found some react components that push the feedback to Slack, but none that create a github issue...

**Comment by prabhant** [comment]
Done
