### ISSUE TITLE
Data Upload with attribute information

### ISSUE THREAD

**Issue by prabhant** [openml/openml.org#131]
Currently, we are assigning attribute types automatically via openml-python. We need to edit the dataset-upload page so that we can specify attributes as a dictionary. like here(https://openml.github.io/openml-python/master/examples/30_extended/create_upload_tutorial.html#sphx-glr-examples-30-extended-create-upload-tutorial-py)
Shall we make it accessible via simple upload page or wait for edit-dataset PR https://github.com/openml/openml-python/issues/929
And add this feature in the new edit dataset page via dash?

**Comment by joaquinvanschoren** [comment]
I would do this as part of dataset editing. Use the automatic type assignment in the initial upload, and allow people to correct it later.

There is a tool called ptype that gives better type prediction than pandas. Ask Marcos. It would be great to integrate it into the Python API.

**Comment by joaquinvanschoren** [comment]
I'm rephrasing this in a new issue.
