### ISSUE TITLE
Study shortlinks no longer working

### ISSUE THREAD

**Issue by mfeurer** [openml/openml.org#152]
Previously, one could go to openml.org/s/99 to get a study, however, with new.openml.org/s/99 this does no longer work, but instead gives:
![image](https://user-images.githubusercontent.com/5320498/98665247-b61ff880-234b-11eb-8e28-0abc9f4e07ba.png)

**Comment by joaquinvanschoren** [comment]
Thanks for reporting. Fixed now thanks to @prabhant.
