### ISSUE TITLE
Formatting issues of Supervised Classification page

### ISSUE THREAD

**Issue by HeidiSeibold** [openml/openml.org#154]
On the task type description [Supervised Classification](https://new.openml.org/search?type=task_type&sort=date&id=1)
I see `<br>`.  

![image](https://user-images.githubusercontent.com/14146757/99952728-69431580-2d80-11eb-9b34-100508ee9040.png)

**Comment by joaquinvanschoren** [comment]
Fixed. Also added markdown support in the process :)
