### ISSUE TITLE
SSL certificate expired on openml.org

### ISSUE THREAD

**Issue by Domimax** [openml/openml.org#167]
Expired certificate preventing access to datasets on the website and unable to use sklearn.fetch_openml function to grab datasets.

![image](https://user-images.githubusercontent.com/44680351/112342241-f740f580-8cb9-11eb-9c25-f524d8c25940.png)

![image](https://user-images.githubusercontent.com/44680351/112342417-1b9cd200-8cba-11eb-8698-2a3b62bf6155.png)

**Comment by Hintro** [comment]
I'm having the same issue.

**Comment by MaiRajborirug** [comment]
I'm having the same issue. Please help!

**Comment by joaquinvanschoren** [comment]
The SSL issue is fixed now. Again apologies for the inconvenience!

Please close the issue if everything is working for you again.

**Comment by Domimax** [comment]
Thank you! This was truly helpful!
