### ISSUE TITLE
Certificate verification failed

### ISSUE THREAD

**Issue by ablaom** [openml/openml.org#168]
I had trouble navigating to openml.org today with two different browsers, getting complaints about non-private something-or-other. And tests for integration with the julia framework MLJ are now failing. It looks like the same issue:

In a julia session (this used to work fine):

```julia
using Pkg
Pkg.activate(temp=true)
Pkg.add("MLJ") 
using MLJ

OpenML.load(61)
Error occurred : IOError(MbedTLS error code -9984: X509 - Certificate verification failed, e.g. CRL, CA or signature check failed during request(https://www.openml.org/api/v1/json/data/61))

ERROR: MethodError: no method matching getindex(::Nothing, ::String)
Stacktrace:
 [1] load(::Int64) at /Users/anthony/.julia/packages/MLJBase/pCCd7/src/openml.jl:110
 [2] top-level scope at REPL[4]:1
```

**Comment by joaquinvanschoren** [comment]
Our SSL certificate expired, we’ve requested a new one and hopefully have it fixed soon. Apologies for the inconvenience!

**Comment by joaquinvanschoren** [comment]
The SSL issue is fixed now. Again apologies for the inconvenience!

Please close the issue if everything is working for you again.

**Comment by ablaom** [comment]
All good now. Thanks for the prompt attention.
