### ISSUE TITLE
confusing mouse-over in histograms on website

### ISSUE THREAD

**Issue by amueller** [openml/openml.org#17]
![image](https://user-images.githubusercontent.com/449558/49119719-7606fe80-f277-11e8-8fda-79a5c5032b39.png)

Doing a mouse-over over one of the bars tells me that there's zero of the other bar. That makes no sense to me. If I hover over the other bar, it gives me the correct number for the other bar and zero for the bar I'm not hovering over.

This makes sense for the features if you want to analyze the features as a function of the default target, but for the default target it's very confusing.

**Comment by joaquinvanschoren** [comment]
This is how that visualization library that we used (highcharts) works. Or worked, I haven't looked at it for a while. I left it that way because sometimes here are many classes and then you need the mouseover to see the actual values.

Will be replaced by a better library in the new frontend.
