### ISSUE TITLE
"Loading wiki..." indicator does not disappear in dataset view

### ISSUE THREAD

**Issue by nocibambi** [openml/openml.org#170]
"Loading wiki..." indicator does not disappear in dataset view

![image](https://user-images.githubusercontent.com/8539674/115015739-6b834900-9eb4-11eb-9a64-579ab0edfbfe.png)

True for both "old" and "new" websites.

**Comment by joaquinvanschoren** [comment]
Thanks for reporting. I restarted the wiki engine.

Please note that we will discontinue this feature soon. The open source wiki engine we are using doesn't scale with the amount of pages that we have. It's also another component that's hard to integrate with the API and maintain, and it's quite unstructured. Therefore, we have implemented our own dataset editing functionality in the new website: https://new.openml.org/d/42159

We hope to release it next month. The wiki engine will then no longer be used.
