### ISSUE TITLE
ARFF link leads nowhere useful

### ISSUE THREAD

**Issue by kdraeder** [openml/openml.org#177]
On https://docs.openml.org/Datasets/
there's a link (ARFF definition ?) to https://waikato.github.io/weka-wiki/arff/
which shows an outline of links,
which lead to 404 errors.
So a better definition of ARFF would be helpful to us newbies.

**Comment by joaquinvanschoren** [comment]
Fixed the link.

**Comment by joaquinvanschoren** [comment]
Thanks for reporting.
