### ISSUE TITLE
Failed to recieve account activation email.  

### ISSUE THREAD

**Issue by Chazcomel** [openml/openml.org#178]
It seems that other users have had this problem in the past and the issue was closed.  Any chance you can activate my account?  chuckcate@gmail.com  Thanks!  (Yes, I have checked spam and it's been a couple of hours since signing up / registering)

Thanks for reporting this problem. What is the email address with which you registered?

_Originally posted by @janvanrijn in https://github.com/openml/openml.org/issues/37#issuecomment-397023618_

**Comment by janvanrijn** [comment]
Did your email arrive in the meantime? Otherwise we could activate it manually.

**Comment by Chazcomel** [comment]
No worries.  I was interested in the Indy 500 this past weekend.  I have
since watched what I need on the Internet.

What was important for me:  I needed to tell you about your website
issues.  There is no way to re-subscribe when your site gives an error
message through your text-message-authentication process.

How many re-subscriptions are you missing?

Chuck

**Comment by Chazcomel** [comment]
Oops.  That was a message for Kayo...  Hah..

let me check on the Github issue.  Best,

Chuck

**Comment by Chazcomel** [comment]
> Did your email arrive in the meantime? Otherwise we could activate it manually.

Yes, please activate it manually.  Thanks!

**Comment by joaquinvanschoren** [comment]
Hi, The account is activated. Cheers!
