### ISSUE TITLE
old website should mention new website

### ISSUE THREAD

**Issue by sebffischer** [openml/openml.org#189]
Why does the website https://www.openml.org/ not mention (or maybe forward) to https://new.openml.org/ ? 
I googled openML, used the first website, only to discover after a while that there is a new website ...

**Comment by sebffischer** [comment]
In addition to that one can reach the old website from the new website, e.g. by 
opening https://docs.openml.org/  and then clicking on "openML" in the top left corner.

**Comment by joaquinvanschoren** [comment]
There are a few key functionalities still missing, but hopefully we can release the new website by the end of the month :)
Also see: https://github.com/openml/openml.org/issues/133
