### ISSUE TITLE
wrong url on contact page - 404 - Not found

### ISSUE THREAD

**Issue by gsverhoeven** [openml/openml.org#220]
Hi there, great project!

On the page https://www.openml.org/contact (Get in touch):

The url underneath `To get help quickly, please [post issues in our GitHub issue trackers]` does not point to github trackers, but to 
`https://docs.openml.org/developers/` which results in a `404 - Not found`.

**Comment by PGijsbers** [comment]
Thanks for reporting the issue! We've been working on a new frontend (new.openml.org), which includes fixed links :) https://new.openml.org/about

**Comment by joaquinvanschoren** [comment]
Closing. Thanks anyway for reporting, @gsverhoeven!

**Comment by gsverhoeven** [comment]
You're welcome!
Have you considered just making the transition to the new frontend and work from there?
Now it is a bit confusing which frontend users should use, test and report issues on.

**Comment by joaquinvanschoren** [comment]
Yes, we will probably make the transition very soon :)
