### ISSUE TITLE
unexpected search behavior when searching for OpenML-Reg19 tagged datasets

### ISSUE THREAD

**Issue by gsverhoeven** [openml/openml.org#221]
Hi there, so far, I am really enjoying the experience of using datasets from OpenML for benchmarking. So thanks for doing this!

Via the tuneRanger package of Philipp Probst I found out about `OpenML-Reg19`, a collection of Regression datasets he created in a similar vein as the CC18.

Coming in as a new user, I thought it might be useful to share my experience / expectations while searching for these datasets on OpenML.

So my first thought was going to `Dataset` and searching with the string `OpenML-Reg19`.
My expectation was that it would return all objects containing this string somewhere in the metadata. Instead I get 22 datasets that upon clicking do not contain the tag `OpenML-Reg19`. Changing the status to `all` gave me 58 datasets, but still not the datasets i was looking for. It was unclear to me why those datasets were returned.

Then I found out, by searching for one of the datasets directly (`tecator`, https://www.openml.org/d/505)  that the datasets i was looking for do contain the tag `OpenML-Reg19`!

So two questions / unexpected behaviors:: 

* why does the dataset `tecator` does not show up when searching for `OpenML-Reg19` ?
* why does it give me all these seemingly unrelated datasets as search result ? 

In the end, I succeeded in listing them by searching specifically using the "tag" filter field, but surprisingly, using **tags.tag:OpenML-Reg19** did **not** work. 
I had to remove the  `OpenML-` part , i.e. search using **tags.tag:Reg19**. This returns the datasets I was looking for.

Is all of this intended behavior?

Regards,
Gertjan

**Comment by gsverhoeven** [comment]
PS:
I was trying this on the old frontend `www.openml.org` , but the issues are still there on the new frontend `new.openml.org`

**Comment by joaquinvanschoren** [comment]
Hi Gertjan,

Thanks for this! Seems like an issue with the search engine. I'll try reindexing it, and then check these issues again.

**Comment by PGijsbers** [comment]
Searching for 'OpenML-Reg19' datasets gives me 24 results.
Filtering for the tag 'OpenML-Reg19' instead gives me 34 results (best I can tell this is the complete collection? Not sure how many to expect).
I can't find 'OpenML-Reg19' suite/study in either old and new front-end.

**Comment by joaquinvanschoren** [comment]
Tag filters seems to work fine now? 
Adding a tag filter 'OpenML-Reg19' when searching for datasets returns 34 datasets, including tecator.
Likewise, Adding a tag filter 'OpenML-Reg19' when searching for tasks also returns the corresponding 34 tasks.

It seems that 'OpenML-Reg19' is just a tag, not an actual collection or benchmark on OpenML.

My suggestion would be to close this issue, and open a new issue asking to make sure that the general search also searches the tags?

**Comment by gsverhoeven** [comment]
I can confirm that, for `new.openml.org` leaving the search field empty and selecting filter on tag 'OpenML-Reg19' now returns the 34 datasets with this tag.
