### ISSUE TITLE
Naming: estimation vs evaluation procedure

### ISSUE THREAD

**Issue by sebffischer** [openml/openml.org#222]
On the website on the left bar, the estimation procedure (name from the API) is called Eval. Procedure

**Comment by joaquinvanschoren** [comment]
What do you think is best / most intuitive? Evaluation procedure is also
commonly used (probably more common that estimation procedure). Or
something else? The website doesn't need to be a 100% match to the API
naming, it should above all be intuitive.

**Comment by sebffischer** [comment]
I don't have any strong feelings, I just thought it was a typo due to the inconsistency with the API.

**Comment by joaquinvanschoren** [comment]
I think we can keep this as is? Please reopen if you feel otherwise.
