### ISSUE TITLE
Can't edit datasets

### ISSUE THREAD

**Issue by sebffischer** [openml/openml.org#260]
When I change the description of a dataset and click the blue edit-button, nothing happens.

**Comment by joaquinvanschoren** [comment]
I just tried and it seems to work. It took a few seconds before the page reacted, though.
Are you sure that the description has not changed? Which dataset?

**Comment by sebffischer** [comment]
Actually there is a red message at the top that says "cannot edit" which I did not see. 

I tried with those datasets: 

- https://www.openml.org/search?type=data&status=active&id=43871&sort=runs
- https://www.openml.org/search?type=data&status=active&id=43873&sort=runs

**Comment by sebffischer** [comment]
I also tried to edit one of the irisis test uploads and I could edit it

**Comment by joaquinvanschoren** [comment]
Strange. I could edit them. No red message.
Which browser?

**Comment by sebffischer** [comment]
I can edit other datasets, only those that I have uploaded myself I cannot edit it seems. Can you try to edit something you uploaded?

**Comment by sebffischer** [comment]
Also this dataset behaves weirdly now: https://www.openml.org/auth/data-edit?id=42903

**Comment by sebffischer** [comment]
now it is working
