### ISSUE TITLE
The SSL certificate of the website seems expired

### ISSUE THREAD

**Issue by xgchena** [openml/openml.org#264]
I noticed the issue because dataset downloading (by [sklearn.datasets.fetch_openml](https://scikit-learn.org/stable/modules/generated/sklearn.datasets.fetch_openml.html#sklearn-datasets-fetch-openml)) failed with error "urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired". Then visited https://www.openml.org , see below screenshot. Could you fix the problem?

<img width="1904" alt="image" src="https://user-images.githubusercontent.com/68292680/172545563-608f1732-0248-4e7c-b9f7-1e236d6ceb26.png">

**Comment by joaquinvanschoren** [comment]
Apologies, we'll renew it asap.

**Comment by vitali-turintech** [comment]
Any update on this, please?

**Comment by joaquinvanschoren** [comment]
Certificates are now renewed. Apologies again for the interruption!

**Comment by xgchena** [comment]
It's working, thanks for the fix.
