### ISSUE TITLE
Website not reachable

### ISSUE THREAD

**Issue by twibiral** [openml/openml.org#327]
Hi, it looks like the openml.org webpage (and subsequently the API access) is down. I tried it with several devices and networks and confirmed it with different tools for checking uptime, like [websiteplanet](https://www.websiteplanet.com/webtools/down-or-not/?dorn=openml.org)

docs.openml.org is still available.

**Comment by twibiral** [comment]
Seems to be solved

**Comment by josvandervelde** [comment]
Hi @twibiral , thanks for your bug report! We indeed had a problem, it's fixed now and should not happen again :)
