### ISSUE TITLE
OpenML Users page filter and sort

### ISSUE THREAD

**Issue by MichaelMMeskhi** [openml/openml.org#65]
When looking at users, top bar has two features. When trying to filter output is: 

```
Filter results by:
No filters defined yet.
```

While you can sort accordingly with pre-defined conditions. Is there a reason for this?

![Screen Shot 2019-04-19 at 2 28 29 PM](https://user-images.githubusercontent.com/13300528/56440579-6f713600-62af-11e9-9110-cf4360bf884d.png)

**Comment by joaquinvanschoren** [comment]
No longer an issue in the new frontend. You must now choose a type before seeing filters.
