### ISSUE TITLE
[old frontend] api key can not be retrieved

### ISSUE THREAD

**Issue by janvanrijn** [openml/openml.org#67]
on test server, see screenshot. 
This has kind of high priority as it prevents users from obtaining their api key. 

<img width="863" alt="Error-test-openml-account" src="https://user-images.githubusercontent.com/2292730/57914003-200e2d80-788e-11e9-953b-441f448f98db.png">

**Comment by joaquinvanschoren** [comment]
fixed

**Comment by janvanrijn** [comment]
Are you sure? which PR?
