### ISSUE TITLE
Differentiating between studies and suites

### ISSUE THREAD

**Issue by prabhant** [openml/openml.org#77]
Currently the studies and suites are displayed under the same section('study'). This creates a problem during the visualization as the python API does not know if it's getting suite or study. So is there any way we can specify study or suites as a frontend tag or make a different page in frontend for suites?

**Comment by joaquinvanschoren** [comment]
There are now different listings in the frontend.

In the frontend, you can check the type with `context.filter.study_type` in the search context, or the `study_type` property of the item itself.

The type is currently either 'run' for run studies (run collections) or 'task' for benchmark suites (task collections).
