### ISSUE TITLE
Google is referencing dead links

### ISSUE THREAD

**Issue by NicolasHug** [openml/openml.org#89]
I've been using the API a bit and googling a lot, and a bunch of time google was sending me to dead links.

For example "openml flows" proposes https://openml.github.io/openml-python/master/examples/flows_and_runs_tutorial.html which gives me a 404.

**Comment by joaquinvanschoren** [comment]
Thanks. Where did you see that link? I cannot find it.

**Comment by NicolasHug** [comment]
IIRC it was in the the top 3 of the search for "openml flows" but indeed it seems to be gone now

**Comment by joaquinvanschoren** [comment]
OK, I guess that was a link to an old version of the openml-python docs that has now been updated. 
Thanks for reporting it, though!
