### ISSUE TITLE
Wish list!

### ISSUE THREAD

**Issue by amueller** [openml/openml.org#9]
Here's things I'd like to see prioritized (feel free to ignore me):

- A landing page with a general search button.
- A search bar on top as on the old page
- clickable tags that bring me to things of the same kind (task, run etc) with the same task.

Btw, I have some nice visualizations for supervised tasks that I'll release soon. They might be interesting for OpenML as well.

**Comment by joaquinvanschoren** [comment]
Thanks!
Yes, please show the visualizations.

**Comment by joaquinvanschoren** [comment]
Done, except for the clickable tags (duplicate #98)
