### ISSUE TITLE
Better visualizations of studies

### ISSUE THREAD

**Issue by joaquinvanschoren** [openml/openml.org#90]
Benchmark studies and Dataset overviews (same plots, only on a different set of datasets):
- plot data qualities of all datasets in the study: 
   - Scatter plot of #instance vs #features, maybe also use color/dot size to add extra dimensions
   - histogram of any data quality, which drop-down to choose the quality

Run studies:
- In the current visualization some y-labels are missing
- use opacity to see multiple overlapping points better
- title and axis label are missing
- mean-value results should have different colors for different methods
- sort tasks by number of instances,...
- block-select point and cross-filter results in other plots
- parallel coordinates

**Comment by prabhant** [comment]
Done except "block-select point and cross-filter results in other plots"

**Comment by prabhant** [comment]
Some problems with current visualizations:

- It takes a long time to load the viz in dash as dash is a bit slow on that 
part.
- hovertemplate is lagging so right now delaying it for later.
- Removed study visulaisation based on study-14 joy plot(it was taking 10 minutes to load).

**Comment by joaquinvanschoren** [comment]
@prabhant What's the status on this?

**Comment by joaquinvanschoren** [comment]
@prabhant What's the status on this?

**Comment by prabhant** [comment]
Need to revisit the requirements again. @PGijsbers quite some changes last time.

**Comment by joaquinvanschoren** [comment]
Seems all solved. Loading is still a bit slow, let's open a new issue for that.
