### ISSUE TITLE
Filter on classes doesn't work

### ISSUE THREAD

**Issue by amueller** [openml/openml.org#99]
https://new.openml.org/search?type=data&sort=runs&qualities.NumberOfClasses=lte_1

Should be number of classes is less than 1 but shows all datasets:
![image](https://user-images.githubusercontent.com/449558/73780472-8c062e00-475c-11ea-8bf7-2839b9bb321a.png)

**Comment by joaquinvanschoren** [comment]
Fixed. Also upgraded to more intuitive filters.

<img width="438" alt="Screenshot 2021-02-10 at 23 03 23" src="https://user-images.githubusercontent.com/1724503/107578564-2f054980-6bf4-11eb-986f-8b6b9057d835.png">
